# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slicebug/cricut/protobufs/CriGeo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&slicebug/cricut/protobufs/CriGeo.proto\"M\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\x10svgConvertCanvas\x18\xf8\n \x01(\x0b\x32\x11.SVGConvertCanvasH\x00\x42\x06\n\x04type\"\x8e\x01\n\x0f\x43ommandResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\rerrorResponse\x18\n \x01(\x0b\x32\x0e.ErrorResponseH\x00\x12>\n\x18svgConvertCanvasResponse\x18\xf8\n \x01(\x0b\x32\x19.SVGConvertCanvasResponseH\x00\x42\x06\n\x04type\"\xed\x01\n\rErrorResponse\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12;\n\x10genericErrorCode\x18\n \x01(\x0e\x32\x1f.ErrorResponse.GenericErrorCodeH\x00\x12Q\n!svgConvertCanvasResponseErrorCode\x18\xf8\n \x01(\x0e\x32#.SVGConvertCanvasResponse.ErrorCodeH\x00\"4\n\x10GenericErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0f\x43OMMAND_INVALID\x10\x01\x42\x06\n\x04\x63ode\"\x1f\n\x10SVGConvertCanvas\x12\x0b\n\x03svg\x18\x01 \x01(\t\"o\n\x18SVGConvertCanvasResponse\x12\x0e\n\x06\x63\x61nvas\x18\x01 \x01(\t\"C\n\tErrorCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x14\n\x10INVALID_SVG_DATA\x10\x01\x12\x13\n\x0fNO_GRAPHIC_DATA\x10\x02\x62\x06proto3')



_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_COMMANDRESPONSE = DESCRIPTOR.message_types_by_name['CommandResponse']
_ERRORRESPONSE = DESCRIPTOR.message_types_by_name['ErrorResponse']
_SVGCONVERTCANVAS = DESCRIPTOR.message_types_by_name['SVGConvertCanvas']
_SVGCONVERTCANVASRESPONSE = DESCRIPTOR.message_types_by_name['SVGConvertCanvasResponse']
_ERRORRESPONSE_GENERICERRORCODE = _ERRORRESPONSE.enum_types_by_name['GenericErrorCode']
_SVGCONVERTCANVASRESPONSE_ERRORCODE = _SVGCONVERTCANVASRESPONSE.enum_types_by_name['ErrorCode']
Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'slicebug.cricut.protobufs.CriGeo_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

CommandResponse = _reflection.GeneratedProtocolMessageType('CommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESPONSE,
  '__module__' : 'slicebug.cricut.protobufs.CriGeo_pb2'
  # @@protoc_insertion_point(class_scope:CommandResponse)
  })
_sym_db.RegisterMessage(CommandResponse)

ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'slicebug.cricut.protobufs.CriGeo_pb2'
  # @@protoc_insertion_point(class_scope:ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)

SVGConvertCanvas = _reflection.GeneratedProtocolMessageType('SVGConvertCanvas', (_message.Message,), {
  'DESCRIPTOR' : _SVGCONVERTCANVAS,
  '__module__' : 'slicebug.cricut.protobufs.CriGeo_pb2'
  # @@protoc_insertion_point(class_scope:SVGConvertCanvas)
  })
_sym_db.RegisterMessage(SVGConvertCanvas)

SVGConvertCanvasResponse = _reflection.GeneratedProtocolMessageType('SVGConvertCanvasResponse', (_message.Message,), {
  'DESCRIPTOR' : _SVGCONVERTCANVASRESPONSE,
  '__module__' : 'slicebug.cricut.protobufs.CriGeo_pb2'
  # @@protoc_insertion_point(class_scope:SVGConvertCanvasResponse)
  })
_sym_db.RegisterMessage(SVGConvertCanvasResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=42
  _COMMAND._serialized_end=119
  _COMMANDRESPONSE._serialized_start=122
  _COMMANDRESPONSE._serialized_end=264
  _ERRORRESPONSE._serialized_start=267
  _ERRORRESPONSE._serialized_end=504
  _ERRORRESPONSE_GENERICERRORCODE._serialized_start=444
  _ERRORRESPONSE_GENERICERRORCODE._serialized_end=496
  _SVGCONVERTCANVAS._serialized_start=506
  _SVGCONVERTCANVAS._serialized_end=537
  _SVGCONVERTCANVASRESPONSE._serialized_start=539
  _SVGCONVERTCANVASRESPONSE._serialized_end=650
  _SVGCONVERTCANVASRESPONSE_ERRORCODE._serialized_start=583
  _SVGCONVERTCANVASRESPONSE_ERRORCODE._serialized_end=650
# @@protoc_insertion_point(module_scope)
