# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NativeModel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11NativeModel.proto*\xe0\x02\n\nPBToolType\x12\x0b\n\x07NONE_TT\x10\x00\x12\x14\n\x10ROLLING_BLADE_TT\x10\x01\x12\x11\n\rDRAG_KNIFE_TT\x10\x02\x12\x17\n\x13TANGENTIAL_BLADE_TT\x10\x03\x12\r\n\tPEN_DT_TT\x10\x04\x12\r\n\tSTYLUS_TT\x10\x05\x12\x14\n\x10SCORING_WHEEL_TT\x10\x06\x12\x18\n\x14PERFORATION_WHEEL_TT\x10\t\x12\x15\n\x11\x44\x45\x42OSSING_TOOL_TT\x10\n\x12\x10\n\x0cWAVE_TOOL_TT\x10\x0b\x12\x13\n\x0f\x45NGRAVE_TOOL_TT\x10\x0c\x12\x16\n\x12MIDAS_FINE_TOOL_TT\x10\r\x12\x19\n\x15MIDAS_REGULAR_TOOL_TT\x10\x0e\x12\x16\n\x12MIDAS_BOLD_TOOL_TT\x10\x0f\x12\x1b\n\x17\x44OUBLE_SCORING_WHEEL_TT\x10\x62\x12\x0f\n\x0b\x44\x45\x45P_CUT_TT\x10\x63*\xfb\x01\n\tPBArtType\x12\x11\n\rNONE_ART_TYPE\x10\x00\x12\x10\n\x0c\x43UT_ART_TYPE\x10\x01\x12\x11\n\rDRAW_ART_TYPE\x10\x02\x12\x12\n\x0eSCORE_ART_TYPE\x10\x04\x12\x13\n\x0f\x44\x45\x42OSS_ART_TYPE\x10\x05\x12\x11\n\rWAVE_ART_TYPE\x10\x06\x12\x14\n\x10\x45NGRAVE_ART_TYPE\x10\x07\x12\x16\n\x12PERFORATE_ART_TYPE\x10\x08\x12\x17\n\x13MIDAS_FINE_ART_TYPE\x10\n\x12\x1a\n\x16MIDAS_REGULAR_ART_TYPE\x10\x0b\x12\x17\n\x13MIDAS_BOLD_ART_TYPE\x10\x0c\x62\x06proto3')

_PBTOOLTYPE = DESCRIPTOR.enum_types_by_name['PBToolType']
PBToolType = enum_type_wrapper.EnumTypeWrapper(_PBTOOLTYPE)
_PBARTTYPE = DESCRIPTOR.enum_types_by_name['PBArtType']
PBArtType = enum_type_wrapper.EnumTypeWrapper(_PBARTTYPE)
NONE_TT = 0
ROLLING_BLADE_TT = 1
DRAG_KNIFE_TT = 2
TANGENTIAL_BLADE_TT = 3
PEN_DT_TT = 4
STYLUS_TT = 5
SCORING_WHEEL_TT = 6
PERFORATION_WHEEL_TT = 9
DEBOSSING_TOOL_TT = 10
WAVE_TOOL_TT = 11
ENGRAVE_TOOL_TT = 12
MIDAS_FINE_TOOL_TT = 13
MIDAS_REGULAR_TOOL_TT = 14
MIDAS_BOLD_TOOL_TT = 15
DOUBLE_SCORING_WHEEL_TT = 98
DEEP_CUT_TT = 99
NONE_ART_TYPE = 0
CUT_ART_TYPE = 1
DRAW_ART_TYPE = 2
SCORE_ART_TYPE = 4
DEBOSS_ART_TYPE = 5
WAVE_ART_TYPE = 6
ENGRAVE_ART_TYPE = 7
PERFORATE_ART_TYPE = 8
MIDAS_FINE_ART_TYPE = 10
MIDAS_REGULAR_ART_TYPE = 11
MIDAS_BOLD_ART_TYPE = 12


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBTOOLTYPE._serialized_start=22
  _PBTOOLTYPE._serialized_end=374
  _PBARTTYPE._serialized_start=377
  _PBARTTYPE._serialized_end=628
# @@protoc_insertion_point(module_scope)
